sudo: required
services:
  - docker

before_install:
  - docker build -t xxmadmanxx/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xxmadmanxx/react-test npm test

after_success:
  - docker build -t xxmadmanxx/multi-client ./client
  - docker build -t xxmadmanxx/multi-nginx ./nginx
  - docker build -t xxmadmanxx/multi-server ./server
  - docker build -t xxmadmanxx/multi-worker ./worker